---
# Ansible playbook
- hosts: ethproxy
  become: True
  become_method: 'sudo'
  vars_files:
    - defaults/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    - include: tasks/main.yml
